// Web Frameworks/React/Session 3 - Hands On/solutions/react-redux-vscode-completed/src/js/components/widget-table.js
import React from 'react';

import { WidgetTableViewRow } from './widget-table-view-row';
import { WidgetTableEditRow } from './widget-table-edit-row';

export class WidgetTable extends React.Component {

    static propTypes = {
        widgets: React.PropTypes.arrayOf(React.PropTypes.shape({
            id: React.PropTypes.number,
            name: React.PropTypes.string,
            description: React.PropTypes.description,
            color: React.PropTypes.string,
            size: React.PropTypes.string,
            quantity: React.PropTypes.number,
        })).isRequired,
        onEdit: React.PropTypes.func.isRequired,
        onDelete: React.PropTypes.func.isRequired,
        onSave: React.PropTypes.func.isRequired,
        onCancel: React.PropTypes.func.isRequired,
        editRowId: React.PropTypes.number.isRequired,
    }    

    render() {

        return <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Color</th>
                    <th>Size</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                {this.props.widgets.map(widget =>
                    widget.id === this.props.editRowId
                        ? <WidgetTableEditRow key={widget.id} widget={widget}
                            onSave={this.props.onSave} onCancel={this.props.onCancel} />
                        : <WidgetTableViewRow key={widget.id} widget={widget}
                            onDelete={this.props.onDelete} onEdit={this.props.onEdit} />
                )}
            </tbody>
        </table>;
    }
}

// Web Frameworks/Angular/Session 2 - Hands On/solutions/angular-vscode-complete/src/ts/app/components/widget-table.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

import { Widget } from "../models/widget";

@Component({
    selector: "widget-table",
    templateUrl: "./widget-table.component.html",
    styleUrls: [ "./widget-table.component.scss" ],
})
export class WidgetTable {

    public editRowId = 0;

    @Input()
    public widgets: Widget[] = [];

    @Output()
    public onSaveWidget: EventEmitter<Widget> = new EventEmitter<Widget>();

    @Output()
    public onDeleteWidget: EventEmitter<number> = new EventEmitter<number>();

    public editWidget(widgetId: number) {
        this.editRowId = widgetId;
    }
}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Color</th>
            <th>Size</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <ng-template ngFor let-widget [ngForOf]="widgets">
            <tr widget-view-row *ngIf="widget.id !== editRowId" [widget]="widget"
                (onEditWidget)="editWidget($event)" (onDeleteWidget)="onDeleteWidget.emit($event); editRowId = 0">
            </tr>
            <tr widget-edit-row *ngIf="widget.id === editRowId" [widget]="widget"
                (onSaveWidget)="onSaveWidget.emit($event); editRowId = 0" (onCancelWidget)="editRowId = 0">
            </tr>
        </ng-template>
    </tbody>
</table>
