// Web Frameworks/Angular/Session 2 - Hands On/solutions/angular-vscode-complete/src/ts/app/components/widget-form.component.ts
import { Component, Output, EventEmitter } from "@angular/core";

import { Widget } from "../models/widget";

@Component({
    selector: "widget-form",
    templateUrl: "./widget-form.component.html",
})
export class WidgetForm {

    newWidget: Widget = {
        id: 0,
        name: "",
        description: "",
        color: "",
        size: "",
        quantity: 0,
    }

    @Output()
    onSubmit: EventEmitter<Widget> = new EventEmitter<Widget>();

    addWidget() {

        this.onSubmit.emit(this.newWidget);

        this.newWidget = {
            id: 0,
            name: "",
            description: "",
            color: "",
            size: "",
            quantity: 0,
        };

    }

}
<h2>Widget Form</h2>
<form>
    <div>
        <label for="widget-name-input">Widget Name:</label>
        <input type="text" name="widgetNameInput" id="widget-name-input" [(ngModel)]="newWidget.name" />
    </div>
    <div>
        <label for="widget-description-input">Widget Description:</label>
        <input type="text" name="widgetDescriptionInput" id="widget-description-input" [(ngModel)]="newWidget.description" />
    </div>
    <div>
        <label for="widget-color-input">Widget Color:</label>
        <input type="text" name="widgetColorInput" id="widget-color-input" [(ngModel)]="newWidget.color" />
    </div>
    <div>
        <label for="widget-size-input">Widget Size:</label>
        <input type="text" name="widgetSizeInput" id="widget-size-input" [(ngModel)]="newWidget.size" />
    </div>
    <div>
        <label for="widget-quantity-input">Widget Quantity:</label>
        <input type="text" name="widgetQuantityInput" id="widget-quantity-input" [(ngModel)]="newWidget.quantity" />
    </div>
    <button type="button" (click)="addWidget()">Add Widget</button>
</form>

// Web Frameworks/React/Session 3 - Hands On/resources/react-redux-vscode-starter/src/js/components/widget-form.js
import React from 'react';

export class WidgetForm extends React.Component {

    static propTypes = {
        onSubmit: React.PropTypes.func
    };

    constructor(props) {
        super(props);

        this.state = {
            name: '',
            description: '',
            color: '',
            size: '',
            quantity: 0,
        };        
    }

    onChange = e => {
        this.setState({
            [e.currentTarget.name]: e.currentTarget.type === 'number'
                ? Number(e.currentTarget.value)
                : e.currentTarget.value
        });
    }

    onClick = () => {
       
        this.props.onSubmit({
            name: this.state.name,
            description: this.state.description,
            color: this.state.color,
            size: this.state.size,
            quantity: this.state.quantity,
        });

        this.setState({
            name: '',
            description: '',
            color: '',
            size: '',
            quantity: 0,
        });
    }    

    render() {
        return <form>
            <div>
                <label htmlFor="widget-name-input">Name:</label>
                <input type="text" id="widget-name-input" name="name"
                    value={this.state.name} onChange={this.onChange} />
            </div>
            <div>
                <label htmlFor="widget-description-input">Description:</label>
                <input type="text" id="widget-description-input" name="description"
                    value={this.state.description} onChange={this.onChange} />
            </div>
            <div>
                <label htmlFor="widget-color-input">Color:</label>
                <input type="text" id="widget-color-input" name="color"
                    value={this.state.color} onChange={this.onChange} />
            </div>
            <div>
                <label htmlFor="widget-size-input">Size:</label>
                <input type="text" id="widget-size-input" name="size"
                    value={this.state.size} onChange={this.onChange} />
            </div>
            <div>
                <label htmlFor="widget-quantity-input">Quantity:</label>
                <input type="number" id="widget-quantity-input" name="quantity"
                    value={this.state.quantity} onChange={this.onChange} />
            </div>
            <button type="button" onClick={this.onClick}>Add Widget</button>
        </form>;
    }

}
